id = "dracula-transparent-theme"
name = "Dracula Transparent"
version = "1.0.0"
schema_version = 1
authors = ["Alex Hill <dev@alexdhill.xyz>", "Ben Hamment <fisix1@gmail.com>"]
description = "Stolen Dracula theme made transparent, for Zed"
repository = "https://github.com/alexdhill/zed-dracula"
